name: Workflow for Concurrency
run-name: Workflow for Concurrency ${{ github.run_number }}
on:
  workflow_dispatch:
    inputs:
      key:
        type: string
        description: 'Key for concurrency control'
        default: pipeline-class
jobs:
  example-flow-exec-01:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.key }}
      cancel-in-progress: true
    steps:
      - name: Execution of Job Test
        run: |
          sleep 120;
          echo "Action completed successfully on Job Test 01";

  example-flow-exec-02:
    runs-on: ubuntu-latest
    needs: [ example-flow-exec-01 ]
    steps:
      - name: Execution of Job Test
        run: |
          sleep 120;
          echo "Action completed successfully on Job Test 02";
