name: Workflow for Concurrency
run-name: Workflow for Concurrency ${{ github.run_number }}
on:
  workflow_dispatch:
    inputs:
      key:
        type: string
        description: 'Key for concurrency control'
        default: pipeline-class
concurrency:
  group: ${{ inputs.key }}
jobs:
  example-flow-exec-01:
    runs-on: ubuntu-latest
    steps:
      - name: Execution of Job Test
        run: |
          sleep 120;
          echo "Action completed successfully on Job Test 01";